// Copyright tang.  All rights reserved.
// Use of this source code is governed by a BSD-style license
package com.cs.core.exec.engine.impl;

import com.cs.common.consts.Constants;
import com.cs.common.enums.NamingStrategyEnum;
import com.cs.common.enums.ProductTypeEnum;
import com.cs.common.exception.CommonException;
import com.cs.common.exception.ResponseErrorCode;
import com.cs.persistence.entity.ApiContextEntity;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

/**
 * GRAPHQL engine end-to-end over an in-memory H2 database (MySQL pagination dialect): field
 * selection pruning, argument/variable binding into MyBatis dynamic SQL, the variables-as-JSON-
 * string debug path, pagination via the apiPageNum/apiPageSize convention, mutations, GraphQL
 * error semantics and the compiled-schema cache.
 */
public class GraphqlExecutorServiceTest {

    private static final String SDL = "type Query {\n" +
            "  users(id: Long, nameLike: String): [User]\n" +
            "    @sql(sql: \"\"\"SELECT id, name, age, birthday FROM t_user WHERE 1=1\n" +
            "      <if test=\"id != null\"> AND id = #{id}</if>\n" +
            "      <if test=\"nameLike != null and nameLike != ''\"> AND name LIKE CONCAT('%', #{nameLike}, '%')</if>\"\"\")\n" +
            "}\n" +
            "type Mutation {\n" +
            "  addUser(name: String): String\n" +
            "    @sql(sql: \"\"\"INSERT INTO t_user(name, age, birthday) VALUES (#{name}, 0, CURRENT_DATE)\"\"\")\n" +
            "}\n" +
            "type User { id: Long  name: String  age: Int  birthday: Date }\n";

    private HikariDataSource dataSource;

    @Before
    public void setUp() throws Exception {
        dataSource = new HikariDataSource();
        // DATABASE_TO_LOWER keeps unquoted identifiers lower case so column labels match the SDL
        // field names after camel-case conversion (H2's default folds them to upper case)
        dataSource.setJdbcUrl("jdbc:h2:mem:graphqlEngine;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS t_user");
            statement.execute("CREATE TABLE t_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(64), age INT, birthday DATE)");
            statement.execute("INSERT INTO t_user(name, age, birthday) VALUES ('alice', 30, '1994-05-06')");
            statement.execute("INSERT INTO t_user(name, age, birthday) VALUES ('bob', 41, '1983-11-02')");
            statement.execute("INSERT INTO t_user(name, age, birthday) VALUES ('carol', 25, '1999-01-31')");
        }
    }

    @After
    public void tearDown() {
        if (null != dataSource) {
            dataSource.close();
        }
    }

    private GraphqlExecutorService engine() {
        return new GraphqlExecutorService(dataSource, ProductTypeEnum.MYSQL);
    }

    private List<ApiContextEntity> sdlContext() {
        return Collections.singletonList(ApiContextEntity.builder().sqlText(SDL).build());
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> execute(String query, Object variables) {
        Map<String, Object> params = new HashMap<>();
        params.put(Constants.PARAM_GRAPHQL_QUERY, query);
        params.put(Constants.PARAM_GRAPHQL_VARIABLES, variables);
        List<Object> results = engine().execute(sdlContext(), params, NamingStrategyEnum.CAMEL_CASE, true);
        Assert.assertEquals(1, results.size());
        return (Map<String, Object>) results.get(0);
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> usersOf(Map<String, Object> result) {
        Assert.assertTrue("expected no errors: " + result.get("errors"),
                null == result.get("errors") || ((List<?>) result.get("errors")).isEmpty());
        return (List<Map<String, Object>>) ((Map<String, Object>) result.get("data")).get("users");
    }

    @Test
    public void fieldSelectionPrunesOutput() {
        List<Map<String, Object>> users = usersOf(execute("{ users { name } }", null));
        Assert.assertEquals(3, users.size());
        Assert.assertEquals("alice", users.get(0).get("name"));
        Assert.assertFalse("unselected column must be pruned", users.get(0).containsKey("id"));
    }

    @Test
    public void longScalarSerializesJdbcValues() {
        List<Map<String, Object>> users = usersOf(execute("{ users { id } }", null));
        Assert.assertEquals(Long.valueOf(1L), users.get(0).get("id"));
    }

    @Test
    public void dateScalarSerializesAsIsoDateString() {
        List<Map<String, Object>> users = usersOf(execute("{ users { name birthday } }", null));
        Assert.assertEquals("1994-05-06", users.get(0).get("birthday"));
    }

    @Test
    public void literalArgumentFiltersRowsThroughDynamicIf() {
        List<Map<String, Object>> users = usersOf(execute("{ users(id: 2) { name } }", null));
        Assert.assertEquals(1, users.size());
        Assert.assertEquals("bob", users.get(0).get("name"));
    }

    @Test
    public void variableArgumentFiltersRowsThroughDynamicIf() {
        List<Map<String, Object>> users = usersOf(
                execute("query($uid: Long) { users(id: $uid) { name } }", Map.of("uid", 1L)));
        Assert.assertEquals(1, users.size());
        Assert.assertEquals("alice", users.get(0).get("name"));
    }

    @Test
    public void stringLikeConditionMatchesSubstring() {
        List<Map<String, Object>> users = usersOf(
                execute("query($n: String) { users(nameLike: $n) { name } }", Map.of("n", "a")));
        Assert.assertEquals(Arrays.asList("alice", "carol"),
                users.stream().map(u -> u.get("name")).collect(java.util.stream.Collectors.toList()));
    }

    @Test
    public void variablesAcceptedAsJsonStringForDebugPath() {
        List<Map<String, Object>> users = usersOf(
                execute("query($uid: Long) { users(id: $uid) { name } }", "{\"uid\": 3}"));
        Assert.assertEquals(1, users.size());
        Assert.assertEquals("carol", users.get(0).get("name"));
    }

    @Test
    public void paginationFollowsApiPageConvention() {
        Map<String, Object> variables = new HashMap<>();
        variables.put(Constants.PARAM_PAGE_NUMBER, 2);
        variables.put(Constants.PARAM_PAGE_SIZE, 2);
        List<Map<String, Object>> users = usersOf(execute("{ users { name } }", variables));
        Assert.assertEquals(1, users.size());
        Assert.assertEquals("carol", users.get(0).get("name"));
    }

    @Test
    public void mutationFieldExecutesInsert() throws Exception {
        Map<String, Object> result = execute("mutation { addUser(name: \"dave\") }", null);
        Assert.assertTrue("expected no errors: " + result.get("errors"),
                null == result.get("errors") || ((List<?>) result.get("errors")).isEmpty());
        Assert.assertEquals("(1) rows affected", ((Map<String, Object>) result.get("data")).get("addUser"));
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM t_user")) {
            Assert.assertTrue(rs.next());
            Assert.assertEquals(4, rs.getInt(1));
        }
    }

    @Test
    public void unknownFieldReportsGraphqlErrorInsteadOfThrowing() {
        Map<String, Object> result = execute("{ missing }", null);
        Assert.assertNull(result.get("data"));
        Assert.assertFalse(((List<?>) result.get("errors")).isEmpty());
    }

    @Test
    public void missingQueryParamRejected() {
        try {
            engine().execute(sdlContext(), Collections.emptyMap(), NamingStrategyEnum.CAMEL_CASE, true);
            Assert.fail("missing query must fail");
        } catch (CommonException e) {
            Assert.assertEquals(ResponseErrorCode.ERROR_INVALID_ARGUMENT, e.getCode());
        }
    }

    @Test
    public void multipleContextsRejected() {
        Map<String, Object> params = new HashMap<>();
        params.put(Constants.PARAM_GRAPHQL_QUERY, "{ users { name } }");
        try {
            engine().execute(Arrays.asList(ApiContextEntity.builder().sqlText(SDL).build(),
                            ApiContextEntity.builder().sqlText(SDL).build()),
                    params, NamingStrategyEnum.CAMEL_CASE, true);
            Assert.fail("multiple SDL documents must fail");
        } catch (CommonException e) {
            Assert.assertEquals(ResponseErrorCode.ERROR_INVALID_ARGUMENT, e.getCode());
        }
    }

    @Test
    public void introspectionAvailableByDefault() {
        Map<String, Object> result = execute("{ __schema { queryType { name } } }", null);
        Map<?, ?> data = (Map<?, ?>) result.get("data");
        Map<?, ?> schema = (Map<?, ?>) data.get("__schema");
        Assert.assertEquals("Query", ((Map<?, ?>) schema.get("queryType")).get("name"));
    }

    @Test
    @SuppressWarnings("unchecked")
    public void compiledSchemaCachedPerSdl() throws Exception {
        Field cacheField = GraphqlExecutorService.class.getDeclaredField("SCHEMA_CACHE");
        cacheField.setAccessible(true);
        Map<String, Object> cache = (Map<String, Object>) cacheField.get(null);
        Assert.assertEquals(3, usersOf(execute("{ users { name } }", null)).size());
        int afterFirst = cache.size();
        Assert.assertEquals(3, usersOf(execute("{ users { name } }", null)).size());
        Assert.assertEquals("identical SDL must reuse the compiled schema", afterFirst, cache.size());
    }
}
